version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: gateway_shareit
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - gv.port=8080
      - sv.url=http://server:9090

  server:
    build: server
    image: server
    container_name: server_shareit
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - db.name=shareit
      - db.username=share
      - db.password=shareit
      - db.port=5432

  db:
    image: postgres:14-alpine
    container_name: db_shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=share
      - POSTGRES_PASSWORD=shareit
